jenkins:
  slaveAgentPort: 0
  agentProtocols:
    - "JNLP3-connect"
    - "JNLP4-connect"
  nodes:
  - jenkins:
      labelString: "master"
      mode: "EXCLUSIVE"
      numExecutors: 0
  authorizationStrategy:
    globalMatrix:
      grantedPermissions:
        - "Overall/Read:anonymous"
        - "Overall/Administer:authenticated"
  clouds:
    - kubernetes:
        name: "{{ k8s_cloud_name }}"
        serverUrl: "{{ k8s_server_url }}"
        skipTlsVerify: true
        namespace: "{{ k8s_namespace }}"
        credentialsId: "advanced-k8s-credentials"
        jenkinsUrl: "{{ jenkins_server_url }}"
        connectTimeout: 0
        readTimeout: 0
        containerCapStr: 100
        maxRequestsPerHostStr: 64
        retentionTimeout: 5
        templates:
          - name: "k8s-slave"
            namespace: "{{ k8s_namespace }}"
            label: "linux-x86_64"
            nodeUsageMode: "EXCLUSIVE"
            containers:
              - name: "jnlp"
                image: "jenkinsci/jnlp-slave:latest"
                alwaysPullImage: true
                workingDir: "/home/jenkins"
                ttyEnabled: true
                resourceRequestCpu: "500m"
                resourceLimitCpu: "1000m"
                resourceRequestMemory: "1Gi"
                resourceLimitMemory: "2Gi"
            volumes:
              - emptyDirVolume:
                  memory: false
                  mountPath: "/tmp"
            idleMinutes: "1"
            activeDeadlineSeconds: "120"
            slaveConnectTimeout: "1000"
credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          scope: "SYSTEM"
          id: "advanced-k8s-credentials"
          username: "{{ k8s_admin_user }}"
          password: "{{ k8s_admin_pass }}"
unclassified:
  location:
    url: "{{ jenkins_server_url }}"