---

- include: check_credentials.yml

- set_fact:
    _rsa_creds: "{{ _rsa_creds|default({}) | combine( {item: item+'.rsa'} ) }}"
  with_items: "{{ jks_credentials }}"

- set_fact:
    _dict_cred_content: "{{ _dict_cred_content|default({}) | combine( { item.key: lookup('template', 'templates/creditem.json', convert_data=False)|replace('\n','') } ) }}"
  with_dict: "{{ _rsa_creds }}"

- name: Add credentials
  uri:
    url: http://127.0.0.1:8080/credentials/store/system/domain/_/createCredentials
    method: POST
    user: "{{ crumb_token.item.key }}"
    password: "{{ crumb_token.item.value }}"
    force_basic_auth: yes
    headers: >
      "{{ jenkins_crumb_token }}" "Content-Type=application/x-www-form-urlencoded"
    body: "{{'json='+item.value|string|replace('\n','\\n') }}"
    status_code: 302
  when: "not {{ _uuid_substr[item.key] | match(uuid_match) }}"
  with_dict: "{{ _dict_cred_content }}"

- include: check_credentials.yml